// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arora.Workflow.Sample.InvoiceApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715031113_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Arora.Workflow.Domain.Aggregates.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeadlineAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status", "DeadlineAt")
                        .HasDatabaseName("ix_aw_approvals_status_deadline");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_aw_approvals_tenant_status");

                    b.HasIndex("TenantId", "WorkflowInstanceId")
                        .HasDatabaseName("ix_aw_approvals_tenant_instance");

                    b.ToTable("aw_approvals", (string)null);
                });

            modelBuilder.Entity("Arora.Workflow.Domain.Aggregates.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_aw_workflow_definitions_tenant_name_version");

                    b.ToTable("aw_workflow_definitions", (string)null);
                });

            modelBuilder.Entity("Arora.Workflow.Domain.Aggregates.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("HistorySequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkflowDefinitionVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_aw_workflow_instances_tenant_idempotency");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_aw_workflow_instances_tenant_status");

                    b.HasIndex("TenantId", "CorrelationId", "WorkflowDefinitionId")
                        .HasDatabaseName("ix_aw_workflow_instances_tenant_correlation");

                    b.ToTable("aw_workflow_instances", (string)null);
                });

            modelBuilder.Entity("Arora.Workflow.Domain.Entities.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status", "AvailableAt");

                    b.ToTable("aw_workflow_work_items", (string)null);
                });

            modelBuilder.Entity("Arora.Workflow.EntityFramework.Entities.WorkflowHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromState")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToState")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "WorkflowInstanceId", "OccurredAt")
                        .HasDatabaseName("ix_aw_workflow_history_tenant_instance_time");

                    b.HasIndex("TenantId", "WorkflowInstanceId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("uq_aw_workflow_history_tenant_instance_sequence");

                    b.ToTable("aw_workflow_history", (string)null);
                });

            modelBuilder.Entity("Arora.Workflow.Domain.Aggregates.Approval", b =>
                {
                    b.OwnsOne("Arora.Workflow.Domain.ValueObjects.ActorInfo", "AssignedActor", b1 =>
                        {
                            b1.Property<Guid>("ApprovalId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("assigned_actor_name");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("assigned_actor_id");

                            b1.HasKey("ApprovalId");

                            b1.ToTable("aw_approvals");

                            b1.WithOwner()
                                .HasForeignKey("ApprovalId");
                        });

                    b.OwnsOne("Arora.Workflow.Domain.ValueObjects.ActorInfo", "DecidedByActor", b1 =>
                        {
                            b1.Property<Guid>("ApprovalId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("decided_by_actor_name");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("decided_by_actor_id");

                            b1.HasKey("ApprovalId");

                            b1.ToTable("aw_approvals");

                            b1.WithOwner()
                                .HasForeignKey("ApprovalId");
                        });

                    b.Navigation("AssignedActor")
                        .IsRequired();

                    b.Navigation("DecidedByActor");
                });

            modelBuilder.Entity("Arora.Workflow.Domain.Aggregates.WorkflowInstance", b =>
                {
                    b.OwnsOne("Arora.Workflow.Domain.ValueObjects.ActorInfo", "CreatedBy", b1 =>
                        {
                            b1.Property<Guid>("WorkflowInstanceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("created_by_name");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("created_by_id");

                            b1.HasKey("WorkflowInstanceId");

                            b1.ToTable("aw_workflow_instances");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowInstanceId");
                        });

                    b.Navigation("CreatedBy")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
